import { Link } from "react-router-dom";

import { FaCalendarAlt, FaClock, FaUser } from "react-icons/all";

import { getTherapistDetails } from "../services/therapistService";

import { useNavigate } from "react-router-dom";

const TherapistProfile = ({ therapistId }) => {
  const navigate = useNavigate();

  const therapistDetails = getTherapistDetails(therapistId);

  if (!therapistDetails) {
    return <div>Therapist not found</div>;
  }

  return (
    <div>
      <h2>{therapistDetails.name}</h2>
      <p>{therapistDetails.email}</p>
      <p>{therapistDetails.phone}</p>
      <p>{therapistDetails.address}</p>
      <p>{therapistDetails.specialty}</p>
      <p>{therapistDetails.experience}</p>
      <p>{therapistDetails.license}</p>
      <p>{therapistDetails.licenseNumber}</p>
      <p>{therapistDetails.licenseState}</p>
      <p>{therapistDetails.licenseType}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>
      <p>{therapistDetails.licenseIssuingAuthority}</p>
      <p>{therapistDetails.licenseStatus}</p>
      <p>{therapistDetails.licenseExpiration}</p>